"""initial_schema

Revision ID: 81ada428ebbe
Revises: 
Create Date: 2026-06-26 21:54:59.261682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ada428ebbe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('patient_name', sa.String(length=128), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_patient_id'), 'patients', ['patient_id'], unique=True)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('plan_label', sa.String(length=128), nullable=False),
    sa.Column('plan_name', sa.String(length=128), nullable=False),
    sa.Column('treatment_site', sa.String(length=64), nullable=True),
    sa.Column('number_of_fractions', sa.Integer(), nullable=True),
    sa.Column('number_of_fields', sa.Integer(), nullable=False),
    sa.Column('dicom_store_path', sa.Text(), nullable=False),
    sa.Column('rtplan_uid', sa.String(length=64), nullable=False),
    sa.Column('rtdose_uid', sa.String(length=64), nullable=True),
    sa.Column('rtstruct_uid', sa.String(length=64), nullable=True),
    sa.Column('qa_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rtplan_uid')
    )
    op.create_index(op.f('ix_plans_patient_id'), 'plans', ['patient_id'], unique=False)
    op.create_table('fractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('fraction_number', sa.Integer(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('rtrecord_uid', sa.String(length=64), nullable=True),
    sa.Column('rtrecord_path', sa.Text(), nullable=True),
    sa.Column('qa_status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fractions_plan_id'), 'fractions', ['plan_id'], unique=False)
    op.create_table('gamma_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('fraction_number', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=32), nullable=False),
    sa.Column('comparison_type', sa.String(length=32), nullable=False),
    sa.Column('dd_percent', sa.Float(), nullable=False),
    sa.Column('dta_mm', sa.Float(), nullable=False),
    sa.Column('passing_rate', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('gamma_map_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamma_results_plan_id'), 'gamma_results', ['plan_id'], unique=False)
    op.create_table('qa_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_jobs_plan_id'), 'qa_jobs', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qa_jobs_plan_id'), table_name='qa_jobs')
    op.drop_table('qa_jobs')
    op.drop_index(op.f('ix_gamma_results_plan_id'), table_name='gamma_results')
    op.drop_table('gamma_results')
    op.drop_index(op.f('ix_fractions_plan_id'), table_name='fractions')
    op.drop_table('fractions')
    op.drop_index(op.f('ix_plans_patient_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_patients_patient_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
